apiVersion: apps/v1
kind: Deployment

metadata:
  name: customer-api

spec:
  replicas: 1

  template:

    spec:

      containers:

      - name: customer-api

        image: customer-api:latest

        resources: {}

        securityContext:
          privileged: true

        ports:
        - containerPort: 8080
``